missing packages, yad

diff --git a/bin/xdg-open b/bin/xdg-open
--- a/bin/xdg-open
+++ b/bin/xdg-open
@@ -6,10 +6,14 @@ if [ "$1" = "-bg" ]; then
     exit
 fi
 
+err () {
+    echo "error: $@" 1>&2
+}
+
 export XDG_OPEN_DEPTH=$(( ${XDG_OPEN_DEPTH:-0} + 1 ))
 
 if [[ $XDG_OPEN_DEPTH -gt 5 ]]; then
-    notify-send "recursive xdg-open looop" "$1"
+    err "recursive xdg-open looop" "$1"
     exit 1
 fi
 
@@ -58,4 +62,12 @@ while read -r mode match; do
     fi
 done < $HOME/.config/open-rules
 
-notify-send "xdg-open failed" "$1 has no matching rule"
+
+CMD=$(yad --center --entry --on-top --completion --entry-label "Open $1 with:" ${(ko)commands})
+
+if [[ $? -eq 0 ]]; then
+    exec "$CMD" "$1"
+else
+    err "xdg-open failed: $1 has no matching rule"
+    exit 1
+fi
